[package]
name = "epix/rojo-template"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
vide = "centau/vide@0.3.1"
ui_labs = "pepeeltoro41/ui-labs@2.3.8"
ripple = "littensy/ripple@0.9.3"
charm = "littensy/charm@0.10.0"
vide_charm = "littensy/vide-charm@0.3.0"
charm_sync = "littensy/charm-sync@0.3.0"
signal = "sleitnick/signal@2.0.3"
typed_remote = "sleitnick/typed-remote@0.3.0"

[server-dependencies]
profile_store = "lm-loleris/profilestore@1.0.3"
